//************************************************ 
//  *Author：jxx
//  *QQ：283591387
//  *代码由框架生成,任何更改都可能导致被代码生成器覆盖
//  *业务请在dataCollection_cjkb.js中编写
//************************************************ 
export default function() {
	return {
		editFormFields: {"gongChang":"","shengChanXian":"","dingDanHao":"","guiGe":"","jrcqrs":"","ywgk":"","mj_rmb":"","mj_sj":"","mj_dcl":"","mj_dbzt":"","yzl_rmb":"","yzl_sj":"","yzl_dcl":"","yzl_dbzt":"","al_rmb":"","al_sj":"","al_dcl":"","al_dbzt":"","sl_rmb":"","sl_sj":"","sl_dcl":"","sl_dbzt":"","jrcqry":""},
		editFormOptions: [{"key":"工厂","data":[],"title":"工厂","field":"gongChang","type":"select"},
                               {"key":"产线-中文","data":[],"title":"生产线","field":"shengChanXian","type":"select"},
                               {"title":"订单号","field":"dingDanHao","type":"text"},
                               {"type":"group"},
                               {"title":"今日出勤人数","field":"jrcqrs","type":"number"},
                               {"title":"规格","field":"guiGe","type":"text"},
                               {"key":"合格不合格","data":[],"title":"异物管控","field":"ywgk","type":"radio"},
                               {"type":"group"},
                               {"title":"母卷日目标","field":"mj_rmb","type":"decimal"},
                               {"title":"母卷实绩","field":"mj_sj","type":"decimal"},
                               {"title":"母卷达成率","field":"mj_dcl","type":"decimal"},
                               {"key":"上升下降","data":[],"title":"母卷对比昨日","field":"mj_dbzt","type":"radio"},
                               {"type":"group"},
                               {"title":"运转率日目标","field":"yzl_rmb","type":"decimal"},
                               {"title":"运转率实绩","field":"yzl_sj","type":"decimal"},
                               {"title":"运转率达成率","field":"yzl_dcl","type":"decimal"},
                               {"key":"上升下降","data":[],"title":"运转率对比昨天","field":"yzl_dbzt","type":"radio"},
                               {"type":"group"},
                               {"title":"A率日目标","field":"al_rmb","type":"decimal"},
                               {"title":"A率实绩","field":"al_sj","type":"decimal"},
                               {"title":"A率达成率","field":"al_dcl","type":"decimal"},
                               {"key":"上升下降","data":[],"title":"A率对比昨天","field":"al_dbzt","type":"radio"},
                               {"type":"group"},
                               {"title":"收率日目标","field":"sl_rmb","type":"decimal"},
                               {"title":"收率实绩","field":"sl_sj","type":"decimal"},
                               {"title":"收率达成率","field":"sl_dcl","type":"decimal"},
                               {"key":"上升下降","data":[],"title":"收率对比昨天","field":"sl_dbzt","type":"radio"},
                               {"type":"group"},
                               {"title":"今日出勤人员","field":"jrcqry","type":"textarea"}],
		searchFormFields: {"gongChang":"","shengChanXian":[],"dingDanHao":""},
		searchFormOptions: [{"key":"工厂","data":[],"title":"工厂","field":"gongChang","type":"select"},{"key":"产线-中文","data":[],"title":"生产线","field":"shengChanXian","type":"selectList"},{"title":"订单号","field":"dingDanHao","type":"text"}],
		columns: [{field:'gongChang',title:'工厂',type:'string',bind:{ key:'工厂',data:[]}},
                       {field:'shengChanXian',title:'生产线',type:'string',bind:{ key:'产线-中文',data:[]}},
                       {field:'dingDanHao',title:'订单号',type:'string'},
                       {field:'guiGe',title:'规格',type:'string'},
                       {field:'jrcqrs',title:'今日出勤人数',type:'int'},
                       {field:'ywgk',title:'异物管控',type:'string',bind:{ key:'合格不合格',data:[]}},
                       {field:'mj_rmb',title:'母卷日目标',type:'decimal'},
                       {field:'mj_sj',title:'母卷实绩',type:'decimal'},
                       {field:'mj_dcl',title:'母卷达成率',type:'decimal'},
                       {field:'mj_dbzt',title:'母卷对比昨日',type:'string',bind:{ key:'上升下降',data:[]}},
                       {field:'yzl_rmb',title:'运转率日目标',type:'decimal'},
                       {field:'yzl_sj',title:'运转率实绩',type:'decimal'},
                       {field:'yzl_dcl',title:'运转率达成率',type:'decimal'},
                       {field:'yzl_dbzt',title:'运转率对比昨天',type:'string',bind:{ key:'上升下降',data:[]}},
                       {field:'al_rmb',title:'A率日目标',type:'decimal'},
                       {field:'al_sj',title:'A率实绩',type:'decimal'},
                       {field:'al_dcl',title:'A率达成率',type:'decimal'},
                       {field:'al_dbzt',title:'A率对比昨天',type:'string',bind:{ key:'上升下降',data:[]}},
                       {field:'sl_rmb',title:'收率日目标',type:'decimal'},
                       {field:'sl_sj',title:'收率实绩',type:'decimal'},
                       {field:'sl_dcl',title:'收率达成率',type:'decimal'},
                       {field:'sl_dbzt',title:'收率对比昨天',type:'string',bind:{ key:'上升下降',data:[]}},
                       {field:'jrcqry',title:'今日出勤人员',type:'string'}],
		table: {
			key: 'id',
			footer: "Foots",
			cnName: '车间看板',
			name: 'dataCollection_cjkb',
			url: "/dataCollection_cjkb/",
			sortName: "CreateDate"
		}
	}
}
